version: '3'
services:
  web:
    build: .
    command: npm run dev
    volumes:
      - .:/usr/app/
      - /usr/app/node_modules
    working_dir: /usr/app
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      NODE_ENV: development
  db:
    build: mysql/
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - dbdata:/var/lib/mysql
  adminer:
    image: adminer:latest
    restart: always
    ports:
      - 8888:8080
    depends_on:
      - db

volumes:
  dbdata: